### ISSUE TITLE
The word "different" repeats itself in README.md

### ISSUE THREAD

**Issue by Ultra980** [AndryCake/x-tux-rice#3]

**Comment by TheGreenGuy5** [comment]
It's an accepted repetition, further explaining where you will be able to find configs for different WMs. "...for different WMs in branches" does not specify in which branches you can find them

**Comment by Ultra980** [comment]
> It's an accepted repetition

Well, it doesn't really work like that...

>"...for different WMs in branches" does not specify in which branches you can find them

I found an alternative
